
// Note: this file is auto-generated by meta_join.js. Don't Modify me !
YUI().use(function(Y) {

	/**
 	* YUI 3 module metadata
 	* @module hexgame-loader
	 */
	var CONFIG = {
		groups: {
			'clicrdv': {
				base: '/Users/michaelweiss/Programs/hexgame/build/',
				combine: false,
				modules: {"hexgame":{"path":"hexgame/hexgame.js","requires":["widget","intl","hexgamemodel","gallery-raphael"],"skinnable":true},"gallery-raphael":{"path":"gallery-raphael/gallery-raphael.js","requires":[]},"hexgamemodel":{"path":"hexgamemodel/hexgamemodel.js","requires":["base"]}}
			}
		}
	};

	if(typeof YUI_config === 'undefined') { YUI_config = {groups:{}}; }
	Y.mix(YUI_config.groups, CONFIG.groups);

});